/**
 * codepend — scanner tests.  `node --test test/`
 *
 * The stakes here are asymmetric: an over-counted human turn is a lie on a card the user is about
 * to screenshot. So most of this file is about what is NOT a human turn.
 *
 * Fixtures are real shapes lifted from ~/.claude and ~/.codex, shortened. Zero dependencies.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

import { parseLines, extractCodexPrompt, wordCount, IDLE_GAP_MS } from '../src/normalize.js';
import { scan } from '../src/scan.js';
import { openCache } from '../src/cache.js';

const j = (o) => JSON.stringify(o);
const T = (iso) => Date.parse(iso);

/* ================================================================== *
 * tokenizer
 * ================================================================== */

test('wordCount is Unicode-aware (Cyrillic counts as words, not bytes)', () => {
  const ru = 'Удали и сделай улучшенную копию, только намного лучше';
  assert.equal(ru.length, 53);          // 53 code points…
  assert.equal(Buffer.byteLength(ru), 98); // …but 98 bytes. Never count bytes.
  assert.equal(wordCount(ru), 8);
  assert.equal(wordCount('hello world'), 2);
  assert.equal(wordCount(''), 0);
  assert.equal(wordCount('emoji 🚀 don’t break it'), 4); // don’t = one token
});

/* ================================================================== *
 * Claude — human turn detection
 * ================================================================== */

const claudeHuman = (ts, text, extra = {}) =>
  j({
    parentUuid: null,
    type: 'user',
    timestamp: ts,
    cwd: '/Users/me/dev/orchard',
    gitBranch: 'main',
    sessionId: 's1',
    version: '2.1.219',
    promptSource: 'sdk',
    origin: { kind: 'human' },
    message: { role: 'user', content: text },
    ...extra,
  });

test('Claude: only origin.kind === "human" counts as a typed prompt', () => {
  const s = parseLines('claude', [
    claudeHuman('2026-07-01T10:00:00.000Z', 'сделай сборку и проверь, что всё работает'),
    // 94 % of `user` lines look like this — tool output, no origin at all.
    j({
      type: 'user',
      timestamp: '2026-07-01T10:00:05.000Z',
      message: {
        role: 'user',
        content: [{ type: 'tool_result', tool_use_id: 'toolu_1', content: 'ok' }],
      },
    }),
    // injected background-task chatter
    j({
      type: 'user',
      timestamp: '2026-07-01T10:00:06.000Z',
      origin: { kind: 'task-notification' },
      message: { role: 'user', content: '<task-notification>done</task-notification>' },
    }),
    // isMeta plumbing
    j({
      type: 'user',
      timestamp: '2026-07-01T10:00:07.000Z',
      isMeta: true,
      origin: { kind: 'human' },
      message: { role: 'user', content: 'Caveat: the messages below were generated by…' },
    }),
    // array content: only `text` blocks are the human's words
    claudeHuman('2026-07-01T10:01:00.000Z', [
      { type: 'text', text: 'and now ship it' },
      { type: 'image', source: { type: 'base64', data: 'iVBOR' } },
    ]),
  ]);

  assert.equal(s.counts.humanTurns, 2);
  assert.deepEqual(
    s.humanTurns.map((t) => t.text),
    ['сделай сборку и проверь, что всё работает', 'and now ship it'],
  );
  assert.equal(s.humanTurns[0].words, 7, 'Cyrillic words counted correctly');
  assert.equal(s.humanTurns[0].ts, T('2026-07-01T10:00:00.000Z'));
});

test('Claude: queue-operation enqueues are a fallback, never a second count', () => {
  const dup = 'исправь баг с таймером';
  const s = parseLines('claude', [
    // A queued prompt that the user really did send → must NOT be counted twice.
    j({
      type: 'queue-operation',
      operation: 'enqueue',
      timestamp: '2026-07-01T09:59:00.000Z',
      content: dup,
    }),
    claudeHuman('2026-07-01T10:00:00.000Z', dup),
    // A queued prompt that never became a user line → counts once.
    j({
      type: 'queue-operation',
      operation: 'enqueue',
      timestamp: '2026-07-01T10:02:00.000Z',
      content: 'Удали и сделай улучшенную копию, только намного лучше',
    }),
    // Injected notification that happens to travel through the queue → never a prompt.
    j({
      type: 'queue-operation',
      operation: 'enqueue',
      timestamp: '2026-07-01T10:03:00.000Z',
      content: '<task-notification>\n<task-id>bg0w8g1r6</task-id>\n</task-notification>',
    }),
    // Typed, then deleted before sending. Not a turn — but we keep it for its own detector.
    j({
      type: 'queue-operation',
      operation: 'remove',
      timestamp: '2026-07-01T10:04:00.000Z',
      content: 'до твоих правок такого не было',
    }),
    j({ type: 'queue-operation', operation: 'dequeue', timestamp: '2026-07-01T10:05:00.000Z' }),
  ]);

  assert.equal(s.counts.humanTurns, 2);
  assert.deepEqual(
    s.humanTurns.map((t) => t.text),
    [dup, 'Удали и сделай улучшенную копию, только намного лучше'],
    'sorted by ts, deduped against the real user line',
  );
  assert.equal(s.unsent.length, 1);
  assert.equal(s.unsent[0].text, 'до твоих правок такого не было');
});

test('Claude: assistant lines give models, tokens, tools, files and thinking', () => {
  const s = parseLines('claude', [
    j({
      type: 'assistant',
      timestamp: '2026-07-01T10:00:10.000Z',
      cwd: '/Users/me/dev/orchard',
      message: {
        model: 'claude-fable-5',
        usage: {
          input_tokens: 10,
          output_tokens: 200,
          cache_read_input_tokens: 5000,
          cache_creation_input_tokens: 300,
        },
        content: [
          { type: 'thinking', thinking: 'x'.repeat(1234) },
          { type: 'text', text: 'Here is the plan.' },
          { type: 'tool_use', name: 'Edit', input: { file_path: '/Users/me/dev/a.js' } },
          { type: 'tool_use', name: 'Bash', input: { command: 'npm test' } },
          { type: 'tool_use', name: 'Agent', input: { prompt: 'go' } },
        ],
      },
    }),
    // '<synthetic>' is an error placeholder: no model vote, no tokens.
    j({
      type: 'assistant',
      timestamp: '2026-07-01T10:00:20.000Z',
      isApiErrorMessage: true,
      message: {
        model: '<synthetic>',
        usage: { input_tokens: 999999, output_tokens: 999999 },
        content: [{ type: 'text', text: 'API Error' }],
      },
    }),
  ]);

  assert.deepEqual(s.models, ['claude-fable-5']);
  // Claude's input_tokens EXCLUDES cache — the three buckets are disjoint, no subtraction.
  assert.deepEqual(s.tokens, { in: 10, out: 200, cacheRead: 5000, cacheWrite: 300, reasoning: 0 });
  assert.deepEqual({ ...s.tools }, { Edit: 1, Bash: 1, Agent: 1 });
  assert.deepEqual(s.filesTouched, ['/Users/me/dev/a.js']);
  assert.equal(s.thinkingChars, 1234);
  assert.equal(s.subagents, 1);
  assert.equal(s.counts.agentTurns, 2, 'the synthetic error message is still an agent turn');
});

test('Claude: titles are appended repeatedly — last wins, custom beats ai', () => {
  const base = [
    j({ type: 'assistant', timestamp: '2026-07-01T10:00:00.000Z', message: { model: 'm', content: [] } }),
    j({ type: 'ai-title', aiTitle: 'first guess' }),
    j({ type: 'ai-title', aiTitle: 'Game freezing during multiplayer' }),
  ];
  assert.equal(parseLines('claude', base).title, 'Game freezing during multiplayer');
  assert.equal(
    parseLines('claude', [...base, j({ type: 'custom-title', customTitle: 'Ночная сборка' })]).title,
    'Ночная сборка',
  );
});

test('Claude: the interrupt marker is an interruption, not a prompt', () => {
  const s = parseLines('claude', [
    j({
      type: 'user',
      timestamp: '2026-07-01T10:00:00.000Z',
      origin: { kind: 'human' },
      message: { role: 'user', content: '[Request interrupted by user for tool use]' },
    }),
  ]);
  assert.equal(s.counts.humanTurns, 0);
  assert.equal(s.interrupts.length, 1);
  assert.equal(s.interrupts[0].durationMs, null, 'Claude has no turn timing to join against');
});

/* ================================================================== *
 * Codex — prompt extraction
 * ================================================================== */

test('extractCodexPrompt: unwraps IDE context, drops machine wrappers, keeps prose', () => {
  // The single highest-risk case: 351 of 1000 real prompts arrive wrapped like this. Dropping
  // everything that starts with '#' would delete a third of the user's words.
  const wrapped =
    '# Context from my IDE setup:\n\n## Open tabs:\n- plan.md: .cursor/plans/plan.md\n\n' +
    '## My request for Codex:\nразбери план и дай критику';
  assert.equal(extractCodexPrompt(wrapped), 'разбери план и дай критику');

  assert.equal(
    extractCodexPrompt('# Chrome tabs:\n- tab\n\n## My request for Codex:\nsummarise this page'),
    'summarise this page',
  );
  assert.equal(
    extractCodexPrompt(
      '<in-app-browser-context source="ambient-tab">…</in-app-browser-context>\n' +
        '## My request for Codex:\nчто тут написано?',
    ),
    'что тут написано?',
  );

  // AGENTS.md injection — machine-authored, never a prompt.
  assert.equal(
    extractCodexPrompt(
      '# AGENTS.md instructions for /Users/me/dev\n\n<INSTRUCTIONS>\n# Agent rules\n</INSTRUCTIONS>',
    ),
    null,
  );
  // <app-context> / <environment_context> / <turn_aborted> / <heartbeat> style blocks.
  assert.equal(extractCodexPrompt('<app-context>\n  <cwd>/Users/me</cwd>\n</app-context>'), null);
  assert.equal(
    extractCodexPrompt('<turn_aborted>\nThe user interrupted the previous turn on purpose.'),
    null,
  );
  assert.equal(extractCodexPrompt('<heartbeat>ping</heartbeat>'), null);
  assert.equal(extractCodexPrompt('<environment_context>\n  <shell>zsh</shell>'), null);

  // A pasted spec really does start with '#'. It is the user's own text — keep it.
  const spec = '# Спецификация — главное меню v3\n\n## Концепция одной строкой\nЖивая сцена.';
  assert.equal(extractCodexPrompt(spec), spec);

  assert.equal(extractCodexPrompt('   '), null);
  assert.equal(extractCodexPrompt(undefined), null);
});

/* ================================================================== *
 * Codex — file-level rules
 * ================================================================== */

const codexMeta = (over = {}, ts = '2026-08-05T05:00:00.000Z') =>
  j({
    timestamp: ts,
    type: 'session_meta',
    payload: {
      session_id: '019f-root',
      id: '019f-root',
      timestamp: '2026-08-05T05:00:00.000Z',
      cwd: '/Users/me/dev/orchard',
      originator: 'Codex Desktop',
      cli_version: '0.147.0',
      source: 'vscode',
      thread_source: 'user',
      git: { branch: 'main', commit_hash: 'abc' },
      ...over,
    },
  });

const codexEvent = (ts, payload) => j({ timestamp: ts, type: 'event_msg', payload });

test('Codex: thread_source is the gate — subagent and automation threads are not the user', () => {
  const body = [codexEvent('2026-08-05T05:01:00.000Z', { type: 'user_message', message: 'hi' })];

  assert.ok(parseLines('codex', [codexMeta(), ...body]), 'thread_source=user is a session');
  assert.ok(
    parseLines('codex', [codexMeta({ thread_source: undefined }), ...body]),
    'legacy files without thread_source are sessions',
  );
  assert.ok(parseLines('codex', [codexMeta({ thread_source: 'realtime_voice' }), ...body]));

  assert.equal(
    parseLines('codex', [
      codexMeta({
        thread_source: 'subagent',
        agent_nickname: 'Plato',
        forked_from_id: '019f-root',
        parent_thread_id: '019f-root',
      }),
      ...body,
    ]),
    null,
    'subagent brief is orchestrator-authored, not typed',
  );
  assert.equal(
    parseLines('codex', [codexMeta({ thread_source: 'automation' }), ...body]),
    null,
    'cron runs are not the user',
  );
  assert.equal(parseLines('codex', body), null, 'no session_meta → not a session file');
});

test('Codex: a subagent file stops reading immediately after session_meta', () => {
  let fed = 0;
  const lines = [
    codexMeta({ thread_source: 'subagent' }),
    codexEvent('2026-08-05T05:01:00.000Z', { type: 'user_message', message: 'never read' }),
  ];
  // parseLines stops on `false`; prove the second line was never consumed by checking the count.
  const s = parseLines(
    'codex',
    lines.map((l) => {
      fed++;
      return l;
    }),
  );
  assert.equal(s, null);
  assert.equal(fed, 2, 'both fixtures materialised, but the parser bailed out on the first');
});

test('Codex: repeated session_meta does not restart the session', () => {
  const s = parseLines('codex', [
    codexMeta(),
    codexEvent('2026-08-05T05:01:00.000Z', { type: 'user_message', message: 'один' }),
    codexMeta({ cwd: '/Users/me/somewhere/else' }), // re-emitted on context reload, 25× in one file
    codexEvent('2026-08-05T05:02:00.000Z', { type: 'user_message', message: 'два' }),
  ]);
  assert.equal(s.counts.humanTurns, 2);
  assert.equal(s.cwd, '/Users/me/dev/orchard');
  assert.equal(s.project, 'orchard');
  assert.equal(s.id, '019f-root');
  assert.equal(s.gitBranch, 'main');
});

test('Codex: response_item/message role:user is never a human turn', () => {
  const s = parseLines('codex', [
    codexMeta(),
    codexEvent('2026-08-05T05:01:00.000Z', { type: 'user_message', message: 'переключись на ветку master' }),
    j({
      timestamp: '2026-08-05T05:01:01.000Z',
      type: 'response_item',
      payload: {
        type: 'message',
        role: 'user',
        content: [{ type: 'input_text', text: '# AGENTS.md instructions for /Users/me/dev' }],
      },
    }),
    j({
      timestamp: '2026-08-05T05:01:02.000Z',
      type: 'response_item',
      payload: {
        type: 'message',
        role: 'user',
        content: [{ type: 'input_text', text: '<app-context>\n<cwd>/Users/me</cwd>\n</app-context>' }],
      },
    }),
  ]);
  assert.equal(s.counts.humanTurns, 1);
  assert.equal(s.humanTurns[0].text, 'переключись на ветку master');
});

test('Codex: tokens sum per-turn deltas, and input excludes the cached part', () => {
  const usage = (input, cached, out, reasoning) => ({
    type: 'token_count',
    info: {
      last_token_usage: {
        input_tokens: input,
        cached_input_tokens: cached,
        cache_write_input_tokens: 0,
        output_tokens: out,
        reasoning_output_tokens: reasoning,
        total_tokens: input + out,
      },
      // Running total — summing THIS is the classic ×N overcount.
      total_token_usage: { input_tokens: 999999, output_tokens: 999999 },
    },
  });
  const s = parseLines('codex', [
    codexMeta(),
    codexEvent('2026-08-05T05:01:00.000Z', usage(19331, 18000, 500, 320)),
    codexEvent('2026-08-05T05:02:00.000Z', usage(27021, 26000, 700, 410)),
    // 0.6 % of records are all-zero with a non-zero total; they must contribute nothing.
    codexEvent('2026-08-05T05:03:00.000Z', {
      type: 'token_count',
      info: {
        last_token_usage: {
          input_tokens: 0,
          cached_input_tokens: 0,
          output_tokens: 0,
          reasoning_output_tokens: 0,
          total_tokens: 21778,
        },
      },
    }),
  ]);
  assert.deepEqual(s.tokens, {
    in: 19331 - 18000 + (27021 - 26000),
    out: 1200,
    cacheRead: 44000,
    cacheWrite: 0,
    reasoning: 730,
  });
});

test('Codex: turn_aborted joins task_started (epoch seconds) for its duration', () => {
  const startedAt = T('2026-08-05T05:00:00.000Z') / 1000; // seconds — sibling fields are ms
  const s = parseLines('codex', [
    codexMeta(),
    codexEvent('2026-08-05T05:00:00.000Z', {
      type: 'task_started',
      turn_id: 'turn-a',
      started_at: startedAt,
    }),
    codexEvent('2026-08-05T05:00:42.000Z', {
      type: 'turn_aborted',
      turn_id: 'turn-a',
      reason: 'interrupted',
    }),
    // A turn whose start was lost to a compaction → duration unknown, not zero, not invented.
    codexEvent('2026-08-05T05:01:00.000Z', {
      type: 'turn_aborted',
      turn_id: 'turn-ghost',
      reason: 'interrupted',
    }),
  ]);
  assert.equal(s.interrupts.length, 2);
  assert.equal(s.interrupts[0].durationMs, 42_000);
  assert.equal(s.interrupts[1].durationMs, null);
});

test('Codex: tools merge function_call + custom_tool_call + external MCP, without double count', () => {
  const call = (ts, payload) => j({ timestamp: ts, type: 'response_item', payload });
  const s = parseLines('codex', [
    codexMeta(),
    call('2026-08-05T05:01:00.000Z', {
      type: 'function_call',
      name: 'exec_command',
      call_id: 'call_1',
      arguments: '{"cmd":"rg -n webhook"}',
    }),
    call('2026-08-05T05:01:01.000Z', { type: 'custom_tool_call', name: 'exec', call_id: 'call_2', input: 'const r = …' }),
    // The MCP end-event for call_1 — the same shell call seen one layer down.
    codexEvent('2026-08-05T05:01:02.000Z', {
      type: 'mcp_tool_call_end',
      call_id: 'call_1',
      invocation: { server: 'shell', tool: 'exec_command' },
    }),
    // node_repl BACKS `exec`; counting its events turned js 1226 into 8865 on the real corpus.
    codexEvent('2026-08-05T05:01:03.000Z', {
      type: 'mcp_tool_call_end',
      call_id: 'call_9',
      invocation: { server: 'node_repl', tool: 'js' },
    }),
    // A genuine third-party MCP call with no function_call record → counted, namespaced.
    codexEvent('2026-08-05T05:01:04.000Z', {
      type: 'mcp_tool_call_end',
      call_id: 'call_7',
      invocation: { server: 'codex_apps', tool: 'gmail.search_emails' },
    }),
    j({
      timestamp: '2026-08-05T05:01:05.000Z',
      type: 'response_item',
      payload: { type: 'function_call_output', call_id: 'call_1', output: 'x'.repeat(5000) },
    }),
  ]);
  assert.deepEqual({ ...s.tools }, {
    exec_command: 1,
    exec: 1,
    'mcp__codex_apps__gmail.search_emails': 1,
  });
  assert.equal(s.counts.toolCalls, 3);
});

test('Codex: patch_apply_end fills filesTouched, only on success', () => {
  const s = parseLines('codex', [
    codexMeta(),
    codexEvent('2026-08-05T05:01:00.000Z', {
      type: 'patch_apply_end',
      success: true,
      changes: {
        '/Users/me/dev/orchard/src/game.js': { type: 'update', unified_diff: '@@ …' },
        '/Users/me/dev/orchard/src/new.js': { type: 'add' },
      },
    }),
    codexEvent('2026-08-05T05:02:00.000Z', {
      type: 'patch_apply_end',
      success: false,
      changes: { '/Users/me/dev/orchard/nope.js': { type: 'update' } },
    }),
  ]);
  assert.deepEqual(s.filesTouched.sort(), [
    '/Users/me/dev/orchard/src/game.js',
    '/Users/me/dev/orchard/src/new.js',
  ]);
});

test('Codex: a memory wipe is counted once, not twice', () => {
  const s = parseLines('codex', [
    codexMeta(),
    j({ timestamp: '2026-08-05T05:01:00.000Z', type: 'compacted', payload: {} }),
    codexEvent('2026-08-05T05:01:00.100Z', { type: 'context_compacted' }),
  ]);
  assert.equal(s.compactions, 1);
});

test('Codex: reasoning keeps the bold headline, and feeds thinkingChars', () => {
  const text = '**Planning safe process termination**\n\nI need to check the pid first…';
  const s = parseLines('codex', [
    codexMeta(),
    codexEvent('2026-08-05T05:01:00.000Z', { type: 'agent_reasoning', text }),
  ]);
  assert.equal(s.reasoning[0].text, 'Planning safe process termination');
  assert.equal(s.thinkingChars, text.length);
  assert.equal(s.maxThinkChars, text.length);
});

test('Codex: model is one vote per session (last turn_context, then thread_settings)', () => {
  const withTurns = parseLines('codex', [
    codexMeta(),
    codexEvent('2026-08-05T05:00:30.000Z', {
      type: 'thread_settings_applied',
      thread_settings: { model: 'gpt-5.6-sol', reasoning_effort: 'high' },
    }),
    j({
      timestamp: '2026-08-05T05:01:00.000Z',
      type: 'turn_context',
      payload: { turn_id: 't1', cwd: '/Users/me/dev/orchard', model: 'gpt-5.3-codex' },
    }),
  ]);
  assert.equal(withTurns.model, 'gpt-5.3-codex');
  assert.ok(withTurns.models.includes('gpt-5.6-sol'));

  const settingsOnly = parseLines('codex', [
    codexMeta(),
    codexEvent('2026-08-05T05:00:30.000Z', {
      type: 'thread_settings_applied',
      thread_settings: { model: 'gpt-5.6-luna' },
    }),
  ]);
  assert.equal(settingsOnly.model, 'gpt-5.6-luna');
});

/* ================================================================== *
 * timing + robustness
 * ================================================================== */

test('durationMs sums active bursts and ignores the "laptop was closed" gaps', () => {
  const ev = (ts) => codexEvent(ts, { type: 'agent_message', message: 'ok' });
  const s = parseLines('codex', [
    codexMeta({}, '2026-08-01T10:00:00.000Z'),
    ev('2026-08-01T10:00:00.000Z'),
    ev('2026-08-01T10:00:30.000Z'), // +30 s   → counts
    ev('2026-08-01T10:05:00.000Z'), // +4.5 m  → counts
    ev('2026-08-04T10:05:00.000Z'), // +3 days → ignored entirely
    ev('2026-08-04T10:06:00.000Z'), // +60 s   → counts
  ]);
  assert.equal(s.durationMs, 30_000 + 270_000 + 60_000);
  assert.ok(s.spanMs > 3 * 24 * 3600 * 1000, 'the naive span is 64× bigger — never use it');
  assert.equal(s.startedAt, T('2026-08-01T10:00:00.000Z'));
  assert.equal(s.endedAt, T('2026-08-04T10:06:00.000Z'));
  assert.ok(IDLE_GAP_MS === 600_000);
});

test('out-of-order timestamps are sorted, never negative', () => {
  const s = parseLines('claude', [
    claudeHuman('2026-07-01T10:00:20.000Z', 'second'),
    claudeHuman('2026-07-01T10:00:00.000Z', 'first'),
  ]);
  assert.equal(s.durationMs, 20_000);
  assert.equal(s.startedAt, T('2026-07-01T10:00:00.000Z'));
  assert.deepEqual(
    s.humanTurns.map((t) => t.text),
    ['first', 'second'],
  );
});

test('a malformed line never kills the file', () => {
  const s = parseLines('claude', [
    claudeHuman('2026-07-01T10:00:00.000Z', 'before'),
    '{"type":"user","timestamp":"2026-07-01T10:00:01.000Z","message":{"content":"tru', // truncated
    'not json at all',
    '',
    claudeHuman('2026-07-01T10:00:02.000Z', 'after'),
  ]);
  assert.equal(s.counts.humanTurns, 2);
  assert.equal(s.counts.skippedLines, 2);
});

test('turn text is truncated but counts reflect the whole thing', () => {
  const long = 'слово '.repeat(2000).trim(); // 2000 words, ~11 999 chars
  const s = parseLines('claude', [claudeHuman('2026-07-01T10:00:00.000Z', long)]);
  const turn = s.humanTurns[0];
  assert.equal(turn.text.length, 2000);
  assert.equal(turn.truncated, true);
  assert.equal(turn.chars, long.length);
  assert.equal(turn.words, 2000);
  assert.equal(s.counts.humanWords, 2000);
});

/* ================================================================== *
 * scan() end-to-end
 * ================================================================== */

async function fixtureHome() {
  const root = await mkdtemp(path.join(os.tmpdir(), 'codepend-test-'));
  const claudeProject = path.join(root, 'claude', 'projects', '-Users-me-dev-orchard');
  await mkdir(claudeProject, { recursive: true });
  await writeFile(
    path.join(claudeProject, 'aaaa-1111.jsonl'),
    [
      claudeHuman('2026-07-01T10:00:00.000Z', 'сделай билд'),
      j({ type: 'ai-title', aiTitle: 'Build the game' }),
      j({
        type: 'assistant',
        timestamp: '2026-07-01T10:00:30.000Z',
        cwd: '/Users/me/dev/orchard',
        message: {
          model: 'claude-opus-5',
          usage: { input_tokens: 1, output_tokens: 2, cache_read_input_tokens: 3 },
          content: [{ type: 'tool_use', name: 'Bash', input: { command: 'ls' } }],
        },
      }),
    ].join('\n') + '\n',
  );
  // Deeper files are subagent transcripts, not sessions — must be ignored.
  await mkdir(path.join(claudeProject, 'aaaa-1111', 'subagents'), { recursive: true });
  await writeFile(
    path.join(claudeProject, 'aaaa-1111', 'subagents', 'sub.jsonl'),
    claudeHuman('2026-07-01T10:00:00.000Z', 'I am a subagent brief') + '\n',
  );

  const codexDay = path.join(root, 'codex', 'sessions', '2026', '08', '05');
  await mkdir(codexDay, { recursive: true });
  await writeFile(
    path.join(codexDay, 'rollout-2026-08-05T10-00-00-019f-root.jsonl'),
    [
      codexMeta(),
      codexEvent('2026-08-05T05:01:00.000Z', {
        type: 'user_message',
        message: '# Chrome tabs:\n- x\n\n## My request for Codex:\nпочини сборку',
      }),
      codexEvent('2026-08-05T05:01:30.000Z', { type: 'agent_message', message: 'Готово.' }),
    ].join('\n'), // note: no trailing newline — a session still being written
  );
  await mkdir(path.join(root, 'codex', 'archived_sessions'), { recursive: true });
  await writeFile(
    path.join(root, 'codex', 'archived_sessions', 'rollout-2026-03-01T09-00-00-019a-sub.jsonl'),
    [
      codexMeta({ id: '019a-sub', thread_source: 'subagent' }),
      codexEvent('2026-03-01T04:00:00.000Z', { type: 'user_message', message: 'You are Plato…' }),
    ].join('\n') + '\n',
  );
  return root;
}

test('scan(): finds both agents, ignores subagent files, reports progress', async (t) => {
  const root = await fixtureHome();
  t.after(() => rm(root, { recursive: true, force: true }));
  const progress = [];

  const sessions = await scan({
    claudeDir: path.join(root, 'claude'),
    codexDir: path.join(root, 'codex'),
    cacheDir: path.join(root, 'cache'),
    onProgress: (p) => progress.push(p),
  });

  assert.equal(sessions.length, 2);
  assert.deepEqual(
    sessions.map((s) => s.agent),
    ['claude', 'codex'],
    'sorted oldest first',
  );
  assert.equal(sessions[0].title, 'Build the game');
  assert.equal(sessions[0].project, 'orchard');
  assert.equal(sessions[1].humanTurns[0].text, 'почини сборку', 'unwrapped, last line has no \\n');
  assert.equal(progress.length, 3, 'one callback per file, subagent file included');
  assert.equal(progress.at(-1).done, progress.at(-1).total);
  assert.equal(sessions.stats.skipped, 1, 'the subagent rollout produced no session');
});

test('scan(): warm cache returns identical sessions without re-reading', async (t) => {
  const root = await fixtureHome();
  t.after(() => rm(root, { recursive: true, force: true }));
  const opts = {
    claudeDir: path.join(root, 'claude'),
    codexDir: path.join(root, 'codex'),
    cacheDir: path.join(root, 'cache'),
  };

  const cold = await scan(opts);
  assert.equal(cold.stats.parsed, 3);
  const warm = await scan(opts);
  assert.equal(warm.stats.parsed, 0);
  assert.equal(warm.stats.cached, 3);
  assert.deepEqual(JSON.parse(JSON.stringify(warm)), JSON.parse(JSON.stringify(cold)));

  const bypassed = await scan({ ...opts, cache: false });
  assert.equal(bypassed.stats.cached, 0);
  assert.equal(bypassed.length, cold.length);
});

test('scan(): a changed file invalidates its cache entry', async (t) => {
  const root = await fixtureHome();
  t.after(() => rm(root, { recursive: true, force: true }));
  const opts = {
    claudeDir: path.join(root, 'claude'),
    codexDir: path.join(root, 'codex'),
    cacheDir: path.join(root, 'cache'),
  };
  await scan(opts);

  const file = path.join(
    root,
    'claude',
    'projects',
    '-Users-me-dev-orchard',
    'aaaa-1111.jsonl',
  );
  const { readFile } = await import('node:fs/promises');
  const prev = await readFile(file, 'utf8');
  await writeFile(file, prev + claudeHuman('2026-07-01T10:05:00.000Z', 'ещё раз') + '\n');

  const again = await scan(opts);
  assert.equal(again.stats.parsed, 1, 'only the changed file is re-read');
  assert.equal(again.find((s) => s.agent === 'claude').counts.humanTurns, 2);
});

test('scan(): --since drops older sessions', async (t) => {
  const root = await fixtureHome();
  t.after(() => rm(root, { recursive: true, force: true }));
  const sessions = await scan({
    claudeDir: path.join(root, 'claude'),
    codexDir: path.join(root, 'codex'),
    cacheDir: path.join(root, 'cache'),
    since: '2026-08-01',
  });
  assert.deepEqual(
    sessions.map((s) => s.agent),
    ['codex'],
  );
});

test('scan(): a line larger than the read chunk is reassembled, not corrupted', async (t) => {
  // Real records reach 2.9 MB; the read buffer is 4 MB. A 6 MB line proves the carry path
  // across multiple chunk boundaries, which is where a hand-rolled line splitter goes wrong.
  const root = await mkdtemp(path.join(os.tmpdir(), 'codepend-big-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  const day = path.join(root, 'codex', 'sessions', '2026', '08', '05');
  await mkdir(day, { recursive: true });
  const huge = 'ы'.repeat(3_000_000); // 3 M code points → 6 MB of UTF-8
  await writeFile(
    path.join(day, 'rollout-2026-08-05T10-00-00-019f-root.jsonl'),
    [
      codexMeta(),
      codexEvent('2026-08-05T05:01:00.000Z', { type: 'agent_message', message: huge }),
      codexEvent('2026-08-05T05:01:10.000Z', { type: 'user_message', message: 'после большого' }),
    ].join('\n') + '\n',
  );

  const [s] = await scan({
    claudeDir: '/nonexistent',
    codexDir: path.join(root, 'codex'),
    cache: false,
  });
  assert.equal(s.counts.agentTurns, 1);
  assert.equal(s.agentTurns[0].chars, 3_000_000, 'the whole line survived the chunk boundaries');
  assert.equal(s.agentTurns[0].text.length, 800, 'stored text is capped');
  assert.equal(s.humanTurns[0].text, 'после большого', 'the line after it still parses');
});

test('scan(): missing roots are normal, not an error', async () => {
  const sessions = await scan({
    claudeDir: '/nonexistent/claude',
    codexDir: '/nonexistent/codex',
    cache: false,
  });
  assert.deepEqual(sessions, []);
});

test('cache: a corrupt cache file is ignored, not fatal', async (t) => {
  const dir = await mkdtemp(path.join(os.tmpdir(), 'codepend-cache-'));
  t.after(() => rm(dir, { recursive: true, force: true }));
  const c1 = await openCache({ dir });
  await writeFile(c1.file, '{not json');
  const c2 = await openCache({ dir });
  assert.equal(c2.get('/whatever', { size: 1, mtimeMs: 1 }), undefined);
});
